name: Pull Request
on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Install Office
        run: choco install office365business

#      - name: Activate Office
#        working-directory: C:\Program Files (x86)\Microsoft Office\Office16
#        run: cscript ospp.vbs /inpkey:$OFFICE_ACTIVATION_CODE
#        env:
#          OFFICE_ACTIVATION_CODE: ${{secrets.OFFICE_ACTIVATION_CODE}} 

      - name: Run Excel
        run: "\"C:/Program Files/Microsoft Office/root/Office16/EXCEL.EXE\""
